# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1461, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.time = QtWidgets.QLabel(self.horizontalWidget)
        self.time.setMinimumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.horizontalLayout_4.addWidget(self.time)
        self.frame = QtWidgets.QFrame(self.horizontalWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_4.addWidget(self.frame)
        self.logo = QtWidgets.QLabel(self.horizontalWidget)
        self.logo.setMinimumSize(QtCore.QSize(350, 50))
        self.logo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.logo.setText("")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout_4.addWidget(self.logo)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.frame_2 = QtWidgets.QFrame(self.horizontalWidget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.shift = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shift.setFont(font)
        self.shift.setAlignment(QtCore.Qt.AlignCenter)
        self.shift.setObjectName("shift")
        self.horizontalLayout_7.addWidget(self.shift)
        self.horizontalLayout.addWidget(self.frame_2)
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.horizontalWidget_3.setFont(font)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graph = QtWidgets.QWidget(self.horizontalWidget_3)
        self.graph.setObjectName("graph")
        self.verticalLayout_2.addWidget(self.graph)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.horizontalWidget_3)
        self.horizontalGroupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalGroupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.horizontalGroupBox.setFont(font)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.time_label = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label.setFont(font)
        self.time_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_2.addWidget(self.time_label)
        self.time_label_2 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_2.setFont(font)
        self.time_label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_2.setObjectName("time_label_2")
        self.horizontalLayout_2.addWidget(self.time_label_2)
        self.time_label_3 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_3.setFont(font)
        self.time_label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_3.setObjectName("time_label_3")
        self.horizontalLayout_2.addWidget(self.time_label_3)
        self.time_label_4 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_4.setFont(font)
        self.time_label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_4.setObjectName("time_label_4")
        self.horizontalLayout_2.addWidget(self.time_label_4)
        self.time_label_5 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_5.setFont(font)
        self.time_label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_5.setObjectName("time_label_5")
        self.horizontalLayout_2.addWidget(self.time_label_5)
        self.time_label_6 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_6.setFont(font)
        self.time_label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_6.setObjectName("time_label_6")
        self.horizontalLayout_2.addWidget(self.time_label_6)
        self.time_label_7 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_7.setFont(font)
        self.time_label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_7.setObjectName("time_label_7")
        self.horizontalLayout_2.addWidget(self.time_label_7)
        self.time_label_8 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_8.setFont(font)
        self.time_label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_8.setObjectName("time_label_8")
        self.horizontalLayout_2.addWidget(self.time_label_8)
        self.time_label_9 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.time_label_9.setFont(font)
        self.time_label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label_9.setObjectName("time_label_9")
        self.horizontalLayout_2.addWidget(self.time_label_9)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.horizontalWidget_3)
        self.horizontalGroupBox_2.setMinimumSize(QtCore.QSize(0, 120))
        self.horizontalGroupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.horizontalGroupBox_2.setFont(font)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.plan = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan.setFont(font)
        self.plan.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan.setLineWidth(1)
        self.plan.setText("")
        self.plan.setTextFormat(QtCore.Qt.PlainText)
        self.plan.setAlignment(QtCore.Qt.AlignCenter)
        self.plan.setObjectName("plan")
        self.horizontalLayout_3.addWidget(self.plan)
        self.plan_2 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_2.setFont(font)
        self.plan_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_2.setLineWidth(1)
        self.plan_2.setText("")
        self.plan_2.setTextFormat(QtCore.Qt.PlainText)
        self.plan_2.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_2.setObjectName("plan_2")
        self.horizontalLayout_3.addWidget(self.plan_2)
        self.plan_3 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_3.setFont(font)
        self.plan_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_3.setLineWidth(1)
        self.plan_3.setText("")
        self.plan_3.setTextFormat(QtCore.Qt.PlainText)
        self.plan_3.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_3.setObjectName("plan_3")
        self.horizontalLayout_3.addWidget(self.plan_3)
        self.plan_4 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_4.setFont(font)
        self.plan_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_4.setLineWidth(1)
        self.plan_4.setText("")
        self.plan_4.setTextFormat(QtCore.Qt.PlainText)
        self.plan_4.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_4.setObjectName("plan_4")
        self.horizontalLayout_3.addWidget(self.plan_4)
        self.plan_5 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_5.setFont(font)
        self.plan_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_5.setLineWidth(1)
        self.plan_5.setText("")
        self.plan_5.setTextFormat(QtCore.Qt.PlainText)
        self.plan_5.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_5.setObjectName("plan_5")
        self.horizontalLayout_3.addWidget(self.plan_5)
        self.plan_6 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_6.setFont(font)
        self.plan_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_6.setLineWidth(1)
        self.plan_6.setText("")
        self.plan_6.setTextFormat(QtCore.Qt.PlainText)
        self.plan_6.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_6.setObjectName("plan_6")
        self.horizontalLayout_3.addWidget(self.plan_6)
        self.plan_7 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_7.setFont(font)
        self.plan_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_7.setLineWidth(1)
        self.plan_7.setText("")
        self.plan_7.setTextFormat(QtCore.Qt.PlainText)
        self.plan_7.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_7.setObjectName("plan_7")
        self.horizontalLayout_3.addWidget(self.plan_7)
        self.plan_8 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_8.setFont(font)
        self.plan_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_8.setLineWidth(1)
        self.plan_8.setText("")
        self.plan_8.setTextFormat(QtCore.Qt.PlainText)
        self.plan_8.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_8.setObjectName("plan_8")
        self.horizontalLayout_3.addWidget(self.plan_8)
        self.plan_9 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plan_9.setFont(font)
        self.plan_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_9.setLineWidth(1)
        self.plan_9.setText("")
        self.plan_9.setTextFormat(QtCore.Qt.PlainText)
        self.plan_9.setAlignment(QtCore.Qt.AlignCenter)
        self.plan_9.setObjectName("plan_9")
        self.horizontalLayout_3.addWidget(self.plan_9)
        spacerItem3 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_2)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(self.horizontalWidget_3)
        self.horizontalGroupBox_3.setMinimumSize(QtCore.QSize(0, 120))
        self.horizontalGroupBox_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.horizontalGroupBox_3.setFont(font)
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.fact = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact.setFont(font)
        self.fact.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact.setText("")
        self.fact.setTextFormat(QtCore.Qt.PlainText)
        self.fact.setAlignment(QtCore.Qt.AlignCenter)
        self.fact.setObjectName("fact")
        self.horizontalLayout_5.addWidget(self.fact)
        self.fact_2 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_2.setFont(font)
        self.fact_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_2.setText("")
        self.fact_2.setTextFormat(QtCore.Qt.PlainText)
        self.fact_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_2.setObjectName("fact_2")
        self.horizontalLayout_5.addWidget(self.fact_2)
        self.fact_3 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_3.setFont(font)
        self.fact_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_3.setText("")
        self.fact_3.setTextFormat(QtCore.Qt.PlainText)
        self.fact_3.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_3.setObjectName("fact_3")
        self.horizontalLayout_5.addWidget(self.fact_3)
        self.fact_4 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_4.setFont(font)
        self.fact_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_4.setText("")
        self.fact_4.setTextFormat(QtCore.Qt.PlainText)
        self.fact_4.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_4.setObjectName("fact_4")
        self.horizontalLayout_5.addWidget(self.fact_4)
        self.fact_5 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_5.setFont(font)
        self.fact_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_5.setText("")
        self.fact_5.setTextFormat(QtCore.Qt.PlainText)
        self.fact_5.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_5.setObjectName("fact_5")
        self.horizontalLayout_5.addWidget(self.fact_5)
        self.fact_6 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_6.setFont(font)
        self.fact_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_6.setText("")
        self.fact_6.setTextFormat(QtCore.Qt.PlainText)
        self.fact_6.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_6.setObjectName("fact_6")
        self.horizontalLayout_5.addWidget(self.fact_6)
        self.fact_7 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_7.setFont(font)
        self.fact_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_7.setText("")
        self.fact_7.setTextFormat(QtCore.Qt.PlainText)
        self.fact_7.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_7.setObjectName("fact_7")
        self.horizontalLayout_5.addWidget(self.fact_7)
        self.fact_8 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_8.setFont(font)
        self.fact_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_8.setText("")
        self.fact_8.setTextFormat(QtCore.Qt.PlainText)
        self.fact_8.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_8.setObjectName("fact_8")
        self.horizontalLayout_5.addWidget(self.fact_8)
        self.fact_9 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fact_9.setFont(font)
        self.fact_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.fact_9.setText("")
        self.fact_9.setTextFormat(QtCore.Qt.PlainText)
        self.fact_9.setAlignment(QtCore.Qt.AlignCenter)
        self.fact_9.setObjectName("fact_9")
        self.horizontalLayout_5.addWidget(self.fact_9)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_3)
        self.verticalLayout.addWidget(self.horizontalWidget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1461, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time.setText(_translate("MainWindow", "date-time"))
        self.label_2.setText(_translate("MainWindow", "Project"))
        self.label_4.setText(_translate("MainWindow", "BDT"))
        self.shift.setText(_translate("MainWindow", " смена №"))
        self.label_5.setText(_translate("MainWindow", "количество за смену"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "ВРЕМЯ"))
        self.time_label.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_3.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_4.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_5.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_6.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_7.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_8.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_9.setText(_translate("MainWindow", "TextLabel"))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "ПЛАН"))
        self.horizontalGroupBox_3.setTitle(_translate("MainWindow", "ФАКТ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

