# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 802)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.time = QtWidgets.QLabel(self.horizontalWidget)
        self.time.setObjectName("time")
        self.horizontalLayout_4.addWidget(self.time)
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.widget = QtWidgets.QWidget(self.horizontalWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4.addWidget(self.widget)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalWidget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graph = QtWidgets.QWidget(self.horizontalWidget_3)
        self.graph.setObjectName("graph")
        self.verticalLayout_2.addWidget(self.graph)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(self.horizontalWidget_3)
        self.horizontalGroupBox_3.setMinimumSize(QtCore.QSize(0, 150))
        self.horizontalGroupBox_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.time_label_10 = QtWidgets.QLabel(self.frame_10)
        self.time_label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_10.setObjectName("time_label_10")
        self.verticalLayout_12.addWidget(self.time_label_10)
        self.plan_10 = QtWidgets.QLabel(self.frame_10)
        self.plan_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_10.setObjectName("plan_10")
        self.verticalLayout_12.addWidget(self.plan_10)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.time_label_11 = QtWidgets.QLabel(self.frame_11)
        self.time_label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_11.setObjectName("time_label_11")
        self.verticalLayout_13.addWidget(self.time_label_11)
        self.plan_11 = QtWidgets.QLabel(self.frame_11)
        self.plan_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_11.setObjectName("plan_11")
        self.verticalLayout_13.addWidget(self.plan_11)
        self.horizontalLayout_5.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.time_label_12 = QtWidgets.QLabel(self.frame_12)
        self.time_label_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_12.setObjectName("time_label_12")
        self.verticalLayout_14.addWidget(self.time_label_12)
        self.plan_12 = QtWidgets.QLabel(self.frame_12)
        self.plan_12.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_12.setObjectName("plan_12")
        self.verticalLayout_14.addWidget(self.plan_12)
        self.horizontalLayout_5.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.time_label_13 = QtWidgets.QLabel(self.frame_13)
        self.time_label_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_13.setObjectName("time_label_13")
        self.verticalLayout_15.addWidget(self.time_label_13)
        self.plan_13 = QtWidgets.QLabel(self.frame_13)
        self.plan_13.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_13.setObjectName("plan_13")
        self.verticalLayout_15.addWidget(self.plan_13)
        self.horizontalLayout_5.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.time_label_14 = QtWidgets.QLabel(self.frame_14)
        self.time_label_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_14.setObjectName("time_label_14")
        self.verticalLayout_16.addWidget(self.time_label_14)
        self.plan_14 = QtWidgets.QLabel(self.frame_14)
        self.plan_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_14.setObjectName("plan_14")
        self.verticalLayout_16.addWidget(self.plan_14)
        self.horizontalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.time_label_15 = QtWidgets.QLabel(self.frame_15)
        self.time_label_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_15.setObjectName("time_label_15")
        self.verticalLayout_17.addWidget(self.time_label_15)
        self.plan_15 = QtWidgets.QLabel(self.frame_15)
        self.plan_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_15.setObjectName("plan_15")
        self.verticalLayout_17.addWidget(self.plan_15)
        self.horizontalLayout_5.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.time_label_16 = QtWidgets.QLabel(self.frame_16)
        self.time_label_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_16.setObjectName("time_label_16")
        self.verticalLayout_18.addWidget(self.time_label_16)
        self.plan_16 = QtWidgets.QLabel(self.frame_16)
        self.plan_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_16.setObjectName("plan_16")
        self.verticalLayout_18.addWidget(self.plan_16)
        self.horizontalLayout_5.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.time_label_17 = QtWidgets.QLabel(self.frame_17)
        self.time_label_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_17.setObjectName("time_label_17")
        self.verticalLayout_19.addWidget(self.time_label_17)
        self.plan_17 = QtWidgets.QLabel(self.frame_17)
        self.plan_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_17.setObjectName("plan_17")
        self.verticalLayout_19.addWidget(self.plan_17)
        self.horizontalLayout_5.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.horizontalGroupBox_3)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.time_label_18 = QtWidgets.QLabel(self.frame_18)
        self.time_label_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_18.setObjectName("time_label_18")
        self.verticalLayout_20.addWidget(self.time_label_18)
        self.plan_18 = QtWidgets.QLabel(self.frame_18)
        self.plan_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_18.setObjectName("plan_18")
        self.verticalLayout_20.addWidget(self.plan_18)
        self.horizontalLayout_5.addWidget(self.frame_18)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_3)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.horizontalWidget_3)
        self.horizontalGroupBox_2.setMinimumSize(QtCore.QSize(0, 150))
        self.horizontalGroupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.time_label = QtWidgets.QLabel(self.frame)
        self.time_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_3.addWidget(self.time_label)
        self.plan = QtWidgets.QLabel(self.frame)
        self.plan.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan.setObjectName("plan")
        self.verticalLayout_3.addWidget(self.plan)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.time_label_2 = QtWidgets.QLabel(self.frame_2)
        self.time_label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_2.setObjectName("time_label_2")
        self.verticalLayout_4.addWidget(self.time_label_2)
        self.plan_2 = QtWidgets.QLabel(self.frame_2)
        self.plan_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_2.setObjectName("plan_2")
        self.verticalLayout_4.addWidget(self.plan_2)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.time_label_3 = QtWidgets.QLabel(self.frame_3)
        self.time_label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_3.setObjectName("time_label_3")
        self.verticalLayout_5.addWidget(self.time_label_3)
        self.plan_3 = QtWidgets.QLabel(self.frame_3)
        self.plan_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_3.setObjectName("plan_3")
        self.verticalLayout_5.addWidget(self.plan_3)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_9 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.time_label_9 = QtWidgets.QLabel(self.frame_9)
        self.time_label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_9.setObjectName("time_label_9")
        self.verticalLayout_11.addWidget(self.time_label_9)
        self.plan_9 = QtWidgets.QLabel(self.frame_9)
        self.plan_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_9.setObjectName("plan_9")
        self.verticalLayout_11.addWidget(self.plan_9)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.time_label_8 = QtWidgets.QLabel(self.frame_8)
        self.time_label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_8.setObjectName("time_label_8")
        self.verticalLayout_10.addWidget(self.time_label_8)
        self.plan_8 = QtWidgets.QLabel(self.frame_8)
        self.plan_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_8.setObjectName("plan_8")
        self.verticalLayout_10.addWidget(self.plan_8)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.time_label_7 = QtWidgets.QLabel(self.frame_7)
        self.time_label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_7.setObjectName("time_label_7")
        self.verticalLayout_9.addWidget(self.time_label_7)
        self.plan_7 = QtWidgets.QLabel(self.frame_7)
        self.plan_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_7.setObjectName("plan_7")
        self.verticalLayout_9.addWidget(self.plan_7)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.time_label_6 = QtWidgets.QLabel(self.frame_6)
        self.time_label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_6.setObjectName("time_label_6")
        self.verticalLayout_8.addWidget(self.time_label_6)
        self.plan_6 = QtWidgets.QLabel(self.frame_6)
        self.plan_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_6.setObjectName("plan_6")
        self.verticalLayout_8.addWidget(self.plan_6)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.time_label_5 = QtWidgets.QLabel(self.frame_5)
        self.time_label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_5.setObjectName("time_label_5")
        self.verticalLayout_7.addWidget(self.time_label_5)
        self.plan_5 = QtWidgets.QLabel(self.frame_5)
        self.plan_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_5.setObjectName("plan_5")
        self.verticalLayout_7.addWidget(self.plan_5)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.horizontalGroupBox_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.time_label_4 = QtWidgets.QLabel(self.frame_4)
        self.time_label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.time_label_4.setObjectName("time_label_4")
        self.verticalLayout_6.addWidget(self.time_label_4)
        self.plan_4 = QtWidgets.QLabel(self.frame_4)
        self.plan_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.plan_4.setObjectName("plan_4")
        self.verticalLayout_6.addWidget(self.plan_4)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_2)
        self.verticalLayout.addWidget(self.horizontalWidget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time.setText(_translate("MainWindow", "date-time"))
        self.label_2.setText(_translate("MainWindow", "Project"))
        self.label_4.setText(_translate("MainWindow", "BDT"))
        self.label_3.setText(_translate("MainWindow", "номер смены"))
        self.label_5.setText(_translate("MainWindow", "количество за смену"))
        self.horizontalGroupBox_3.setTitle(_translate("MainWindow", "ПЛАН"))
        self.time_label_10.setText(_translate("MainWindow", "TextLabel"))
        self.plan_10.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_11.setText(_translate("MainWindow", "TextLabel"))
        self.plan_11.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_12.setText(_translate("MainWindow", "TextLabel"))
        self.plan_12.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_13.setText(_translate("MainWindow", "TextLabel"))
        self.plan_13.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_14.setText(_translate("MainWindow", "TextLabel"))
        self.plan_14.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_15.setText(_translate("MainWindow", "TextLabel"))
        self.plan_15.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_16.setText(_translate("MainWindow", "TextLabel"))
        self.plan_16.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_17.setText(_translate("MainWindow", "TextLabel"))
        self.plan_17.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_18.setText(_translate("MainWindow", "TextLabel"))
        self.plan_18.setText(_translate("MainWindow", "TextLabel"))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "ФАКТ"))
        self.time_label.setText(_translate("MainWindow", "TextLabel"))
        self.plan.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_2.setText(_translate("MainWindow", "TextLabel"))
        self.plan_2.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_3.setText(_translate("MainWindow", "TextLabel"))
        self.plan_3.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_9.setText(_translate("MainWindow", "TextLabel"))
        self.plan_9.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_8.setText(_translate("MainWindow", "TextLabel"))
        self.plan_8.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_7.setText(_translate("MainWindow", "TextLabel"))
        self.plan_7.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_6.setText(_translate("MainWindow", "TextLabel"))
        self.plan_6.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_5.setText(_translate("MainWindow", "TextLabel"))
        self.plan_5.setText(_translate("MainWindow", "TextLabel"))
        self.time_label_4.setText(_translate("MainWindow", "TextLabel"))
        self.plan_4.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

